create table DemoDB (
	ID INT,
	Name VARCHAR(50),
	Quantity INT,
	Price VARCHAR(50),
	Status VARCHAR(50)
);
insert into DemoDB (ID, Name, Quantity, Price, Status) values (1, 'Better Tomorrow, A (Ying hung boon sik)', 29, '$17.03', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (2, 'Night Listener, The', 32, '$20.23', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (3, 'Pepi, Luci, Bom (Pepi, Luci, Bom y Otras Chicas del Montón)', 77, '$16.68', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (4, 'Match Factory Girl, The (Tulitikkutehtaan tyttö)', 84, '$18.17', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (5, 'Misérables in Concert, Les', 55, '$15.58', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (6, 'Nine Deaths of the Ninja', 73, '$22.46', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (7, 'That Obscure Object of Desire (Cet obscur objet du désir)', 56, '$19.67', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (8, 'Tabu: A Story of the South Seas', 90, '$16.85', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (9, 'I Like Killing Flies', 54, '$13.68', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (10, 'You Light Up My Life', 92, '$17.05', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (11, 'Ten North Frederick', 91, '$12.45', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (12, 'Fourth State, The (Die vierte Macht)', 96, '$22.83', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (13, 'Great White Silence, The', 82, '$23.62', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (14, 'Return of Swamp Thing, The', 88, '$15.17', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (15, 'Mademoiselle Chambon', 64, '$18.02', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (16, 'Padrecito, El (Little Priest)', 38, '$14.52', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (17, 'Days of Wine and Roses', 62, '$16.81', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (18, 'Barfi!', 63, '$14.57', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (19, 'Pleasure Seekers, The', 67, '$21.52', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (20, 'Red''s Dream', 24, '$20.73', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (21, 'Robot Stories', 98, '$18.05', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (22, 'Kaleidoscope', 54, '$12.21', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (23, 'New York Ripper, The (Squartatore di New York, Lo)', 91, '$21.24', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (24, 'Lady Takes a Chance, A', 12, '$17.90', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (25, 'Story of Qiu Ju, The (Qiu Ju da guan si)', 1, '$14.05', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (26, 'Man Hunt', 36, '$13.62', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (27, 'Mickey''s Twice Upon a Christmas', 70, '$21.16', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (28, 'Frontrunners', 77, '$17.56', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (29, 'Campus Radio', 39, '$22.43', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (30, 'Christopher Columbus: The Discovery', 78, '$19.22', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (31, 'Save the Date', 63, '$20.13', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (32, 'Margaret Cho: Assassin', 20, '$21.52', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (33, 'Dream Land', 78, '$16.42', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (34, 'Death Takes a Holiday', 83, '$14.61', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (35, 'Terror of Mechagodzilla (Mekagojira no gyakushu)', 96, '$19.03', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (36, 'Elstree Calling', 29, '$12.41', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (37, 'K-PAX', 5, '$19.74', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (38, 'Force of One, A', 26, '$14.25', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (39, 'Even Dwarfs Started Small (Auch Zwerge haben klein angefangen)', 81, '$22.38', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (40, 'Intimate Lighting (Intimni osvetleni)', 75, '$19.97', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (41, 'Casa de los babys', 55, '$16.73', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (42, 'And Along Come Tourists (Am Ende kommen Touristen)', 89, '$23.39', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (43, 'Colour Me Kubrick: A True...ish Story', 95, '$14.23', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (44, 'Die, Monster, Die!', 68, '$12.58', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (45, 'Pirates of the Caribbean: On Stranger Tides', 35, '$22.84', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (46, 'Avengers Confidential: Black Widow & Punisher', 37, '$16.10', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (47, 'Yoo-Hoo, Mrs. Goldberg', 40, '$23.76', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (48, 'Rudolph the Red-Nosed Reindeer: The Movie', 21, '$17.04', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (49, '30 Beats', 90, '$22.76', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (50, '976-EVIL', 36, '$15.95', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (51, 'Devil in the Flesh', 88, '$16.70', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (52, 'Woodmans, The', 58, '$20.38', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (53, 'Les hautes solitudes', 90, '$17.68', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (54, 'It''s a Very Merry Muppet Christmas Movie', 30, '$20.88', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (55, 'Outer Space', 22, '$21.59', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (56, 'In the Realms of the Unreal', 41, '$23.00', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (57, 'Summer in Berlin (Sommer vorm Balkon)', 56, '$20.56', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (58, 'Unbreakable', 5, '$13.36', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (59, 'BloodRayne: The Third Reich', 16, '$18.68', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (60, 'Yes Men, The', 89, '$18.91', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (61, 'Hatful of Rain, A', 2, '$23.45', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (62, 'True Blue ', 74, '$23.03', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (63, 'Ocean Heaven ', 99, '$17.42', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (64, 'The Remaining', 92, '$13.90', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (65, 'Prince of Pennsylvania, The', 30, '$20.34', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (66, 'Transformers: Age of Extinction', 66, '$23.19', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (67, 'Four Stories of St. Julian ', 41, '$14.92', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (68, 'Million Dollar Baby', 29, '$15.89', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (69, 'House of D', 31, '$12.47', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (70, 'Carny', 23, '$14.29', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (71, 'The Day I Saw Your Heart', 30, '$20.33', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (72, 'Seven Days in Utopia', 91, '$22.76', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (73, 'Hannibal Rising', 100, '$15.59', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (74, 'Sick Girl', 43, '$12.60', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (75, 'Des gens qui s''embrassent', 41, '$21.26', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (76, 'Spasmo', 8, '$17.85', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (77, 'Morgan Stewart''s Coming Home', 2, '$15.98', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (78, 'Cape Fear', 83, '$12.83', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (79, 'Changing Sides (De l''autre côté du lit)', 56, '$16.38', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (80, 'August (Elokuu) ', 64, '$12.56', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (81, 'Robocroc', 35, '$13.18', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (82, 'Luminarias', 75, '$13.05', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (83, 'Mouse Hunt', 83, '$15.04', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (84, 'Secretariat', 64, '$13.90', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (85, 'Blue Light, The (Blaue Licht, Das)', 99, '$17.98', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (86, 'My Brother the Terrorist', 24, '$14.48', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (87, 'Morphia (Morfiy)', 93, '$12.98', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (88, 'Kicked in the Head', 13, '$14.29', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (89, 'As If I Didn''t Exist (Elina - Som om jag inte fanns)', 31, '$17.46', 'pending');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (90, 'Death of a Salesman', 29, '$22.06', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (91, 'The Hellions', 64, '$20.06', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (92, 'Man on the Moon', 88, '$13.91', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (93, 'Rio Rita', 26, '$16.64', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (94, 'Bad News Bears, The', 61, '$15.11', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (95, 'Love''s Deadly Triangle: The Texas Cadet Murder', 22, '$13.79', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (96, 'The Photographer', 64, '$16.34', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (97, 'El Dorado', 57, '$19.37', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (98, 'Pajeczarki', 97, '$15.52', 'shipped');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (99, 'Broken Embraces (Los abrazos rotos)', 6, '$22.34', 'complete');
insert into DemoDB (ID, Name, Quantity, Price, Status) values (100, 'Dark Girls', 82, '$22.14', 'complete');